### ISSUE TITLE
Missing config on how to connect to jenkins remotely

### ISSUE THREAD

**Issue by rafiki270** [fastlane/jenkins-app#1]
Could you please provide info on how to access the jenkins remotely ... or how to change the HTTP_HOST value to 0.0.0.0?

**Comment by KrauseFx** [comment]
There shouldn't be any change on this.

**Comment by KrauseFx** [comment]
Do you still run into this issue?

**Comment by KrauseFx** [comment]
I'll close this issue for now, feel free to re-open :+1:
